# Generated by Django 4.1.1 on 2022-09-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueprint_name', models.CharField(max_length=200, unique=True, verbose_name='Blueprint name')),
            ],
            options={
                'verbose_name': 'Blueprint',
                'verbose_name_plural': 'Blueprints',
            },
        ),
        migrations.CreateModel(
            name='PartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200, unique=True, verbose_name='Part name')),
                ('measure_unit', models.CharField(max_length=20, verbose_name='Measure unit')),
                ('url', models.CharField(max_length=200, verbose_name='Shop URL')),
                ('price_per_unit', models.FloatField(verbose_name='Unit price')),
            ],
            options={
                'verbose_name': 'Part List',
                'verbose_name_plural': 'Part Lists',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(default=0, verbose_name='Part income')),
                ('usage', models.IntegerField(default=0, verbose_name='Part usage')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction date')),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.partlist')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateTimeField(auto_now_add=True, verbose_name='Production date')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.blueprint')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='Item quantity')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.blueprint')),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.partlist')),
            ],
            options={
                'verbose_name': 'BOM',
                'verbose_name_plural': 'BOMs',
            },
        ),
    ]
