# Generated by Django 4.1.1 on 2022-09-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='item_id',
            new_name='blueprint_id',
        ),
    ]
