# Generated by Django 4.1.1 on 2022-09-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_item_id_device_blueprint_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bom',
            old_name='item_id',
            new_name='blueprint_id',
        ),
    ]
