# Generated by Django 4.1.1 on 2022-10-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_item_id_bom_blueprint_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartList',
            new_name='Part',
        ),
    ]
