# Generated by Django 4.1.1 on 2022-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_partlist_part'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AddField(
            model_name='device',
            name='parts_price',
            field=models.FloatField(default=0, verbose_name='Total parts price'),
        ),
    ]
