# Generated by Django 4.1.1 on 2022-10-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_part_options_device_parts_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='price_per_unit',
        ),
        migrations.AddField(
            model_name='inventory',
            name='price_per_unit',
            field=models.FloatField(default=0, verbose_name='Unit price'),
        ),
    ]
