# Generated by Django 4.1.1 on 2022-10-09 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_part_price_per_unit_inventory_price_per_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bom',
            old_name='blueprint_id',
            new_name='blueprint',
        ),
        migrations.RenameField(
            model_name='bom',
            old_name='part_id',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='blueprint_id',
            new_name='blueprint',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='part_id',
            new_name='part',
        ),
        migrations.AddField(
            model_name='inventory',
            name='blueprint',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.blueprint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.device'),
            preserve_default=False,
        ),
    ]
