# Generated by Django 4.1.1 on 2022-10-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_blueprint_id_bom_blueprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='blueprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.blueprint'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.device'),
        ),
    ]
